name: CI/CD (Build and Artifact)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Job to build .NET sample app
  dotnet-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core & Build
        uses: actions/setup-dotnet@v1.8.2
        with:
          # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 5.0.x
      - run: dotnet publish --configuration Release -o publish
        working-directory: source/WebAppOnVmss
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          # name: # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: source/WebAppOnVmss/publish 
          